server:
  port: 8001
spring:
  application:
    name: sc-payment-service
  zipkin:
    # 放到 zipkin上
    base-url: http://localhost:9411
  #用于sleuth监控
  sleuth:
    sampler:
      # 采样率介于0-1之间，1表示全部采集
      probability: 1
  datasource:
    url: jdbc:mysql://localhost:3306/pay?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  # model的包
  type-aliases-package: com.xuzf.entities
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰uName自动映射到u_name
  mapper-locations: classpath:mapper/*.xml

# 打印sql
logging:
  level:
    ssm.app.mapper : debug
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    instance-id: payment-01
    prefer-ip-address: true