server:
  port: 3344

spring:
  application:
    name: sc-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Suancaiyu0707/spring-cloud-config
          ##搜索目录.这个目录指的是github上的目录
          search-paths: /
          timeout: 15
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001/eureka
#rabbitmq配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
#暴露bus刷新配置端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
